name: Deploy to AKS

on:
  push:
    branches:
      - Azure-kubernetes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up AKS credentials
      run: |
        az aks get-credentials --resource-group neuraLife --name neuralife-backend

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name nerualifebackend

    - name: Build and push Docker images
      run: |
        docker buildx build --push --tag nerualifebackend.azurecr.io/myapp:latest ./app
        docker buildx build --push --tag nerualifebackend.azurecr.io/mydatacollection:latest ./datacollection
        docker buildx build --push --tag nerualifebackend.azurecr.io/mywebpage:latest ./webpage

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl get services