name: Deploy to AKS

on:
  push:
    branches:
      - Azure-kubernetes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up AKS credentials
      run: |
        az aks get-credentials --resource-group neuraLife --name neuralife-backend --overwrite-existing

    - name: Get ACR Access Token
      id: acr_login
      run: |
        az acr login --name neuralifebackend --expose-token > acr_token.json
        echo "::set-output name=acr_username::00000000-0000-0000-0000-000000000000"
        echo "::set-output name=acr_password::$(jq -r .accessToken acr_token.json)"

    - name: Log in to Azure Container Registry
      run: |
        docker login neuralifebackend.azurecr.io --username ${{ steps.acr_login.outputs.acr_username }} --password ${{ steps.acr_login.outputs.acr_password }}

    - name: Build and push Docker images
      run: |
        docker buildx build --push --tag neuralifebackend.azurecr.io/myapp:latest ./app
        docker buildx build --push --tag neuralifebackend.azurecr.io/mydatacollection:latest ./datacollection
        docker buildx build --push --tag neuralifebackend.azurecr.io/mywebpage:latest ./webpage

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/nginx-ingress-controller.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/hpa.yaml
        kubectl get services