name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/my-fastapi-app .
        docker push your-dockerhub-username/my-fastapi-app

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull your-dockerhub-username/my-fastapi-app
          docker stop my-fastapi-app || true
          docker rm my-fastapi-app || true
          docker run -d -p 80:8000 --name my-fastapi-app your-dockerhub-username/my-fastapi-app
